---
title: "NDB"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
```


```{r}
# make folder all in rds for saving data frame

dir.create("../rds/oral/dem",
             showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../rds/ext/dem",
             showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../rds/inj/dem",
             showWarnings = TRUE, recursive = FALSE, mode = "0777")

```

```{r}
# get folder names

folder_oral <- list.files("../xlsx/oral") 

folder_oral
```

```{r}
#dir.create("../rds/parse/12",
#             showWarnings = TRUE, recursive = FALSE, mode = "0777")

#dir.create("../rds/parse/39",
#             showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


```{r}

```


# read first two files

```{r}
get_data_dem_1 <- function(xlsx_path){
  
  # read excel sheet
  df <- read.xlsx(xlsx_path, startRow = 4,
                 fillMergedCells = FALSE) 
  
  # get sheet name
  sheet_name <- getSheetNames(xlsx_path)
  
  # clean colnames
  colnames(df)[1:8] <- c("CLASS_code", "CLASS_name",
                       "DRUG_code", "DRUG_name",
                       "COST_code", "COST_per",
                       "GEN", "TOTAL")

  start <- seq(0, 85, 5)
  end <- seq(4, 89, 5)
  
  range <- paste0(start, "_", end)
  range <- c(range, "90_")
  
  age_sex <- c(paste0("M_", range), paste0("F_", range))
  
  colnames(df)[9:46] <- age_sex
  
  # add file name
  df <- df %>% mutate(FILE_ori = xlsx_path) %>%
    mutate(FILE = str_extract(FILE_ori, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    relocate(FILE, .before = "CLASS_code")
  
  # add sheet name and type
  df <- df %>% mutate(SHEET_jp = sheet_name) %>%
    mutate(TYPE = case_when(str_detect(SHEET_jp, "内服")　~ "oral",
                            str_detect(SHEET_jp, "外用") ~ "ext",
                            str_detect(SHEET_jp, "注射") ~ "inj")) %>%
    relocate(TYPE, .after = "FILE")
    
  
  # add category: dem
  df <- df %>% 
    mutate(CAT = "dem") %>%
    relocate(CAT, .after = "TYPE") 
  
  # add sheet
  df <- df %>%
    mutate(SHEET = case_when(str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院内")~ "outpt_inpr",
                             str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院外")~ "outpt_outpr",
                             str_detect(SHEET_jp, "入院") ~ "inpt")) %>%
    relocate(SHEET, .after = "CAT")

  # add sheet
  df <- df %>% select(!FILE_ori)
  
  
  # fill missing cells 
  df <- df %>%
    tidyr::fill(starts_with("CLASS_"), .direction = "down")
  
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow = 1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  df_year <- get_year(xlsx_path)
    
  df <- df %>% left_join(df_year, by = join_by(FILE))
  

  df <- df %>% mutate(across(everything(), as.character))
  
  return(df)

  }
```

```{r}
df_ex <- get_data_dem_1("../xlsx/oral/inpt_dem/0000139845.xlsx")
```



```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (oral ext inj)
# y is the individual folder

save_df_dem_1 <- function(x, y){
  xlsx <- list.files(paste0("../xlsx/", x, "/", y))
  
  xlsx <- xlsx[1:2]
  
  from <- paste0("../xlsx/", x, "/", y, "/", xlsx)
  
  df <- map(from, get_data_dem_1) %>% list_rbind()
  
  saveRDS(df, paste0("../rds/", x, "/", "dem/", "df_", x, "_", y, "_1"))
}
```

```{r}
folder_oral_dem <- folder_oral %>% str_subset("dem")

folder_oral_dem
```

```{r}
#list.files(paste0("../xlsx/", "oral", "/", oral_dem_xlsx[1]))
```

```{r}
# save file 1 and 2
for (i in 1:length(folder_oral_dem)){
  save_df_dem_1("oral", folder_oral_dem[i])
  print(paste0(folder_oral_dem[i], "_1", " completed"))
}
```

# save 3-9

```{r}
get_data_dem_2 <- function(xlsx_path){
  
  # read excel sheet
  df <- read.xlsx(xlsx_path, startRow = 4,
                 fillMergedCells = FALSE) 
  
  # get sheet name
  sheet_name <- getSheetNames(xlsx_path)
  
  
  # clean colnames
  colnames(df)[1:9] <- c("CLASS_code", "CLASS_name",
                       "DRUG_code", "DRUG_name", "UNIT",
                       "COST_code", "COST_per",
                       "GEN", "TOTAL")
  
  start <- seq(0, 95, 5)
  end <- seq(4, 99, 5)
  
  range <- paste0(start, "_", end)
  range <- c(range, "100_")
  
  age_sex <- c(paste0("M_", range), paste0("F_", range))
  
  colnames(df)[10:51] <- age_sex
  
  # add file name
  df <- df %>% mutate(FILE_ori = xlsx_path) %>%
    mutate(FILE = str_extract(FILE_ori, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    relocate(FILE, .before = "CLASS_code")

   # add sheet name and type
  df <- df %>% mutate(SHEET_jp = sheet_name) %>%
    mutate(TYPE = case_when(str_detect(SHEET_jp, "内服")　~ "oral",
                            str_detect(SHEET_jp, "外用") ~ "ext",
                            str_detect(SHEET_jp, "注射") ~ "inj")) %>%
    relocate(TYPE, .after = "FILE")
    
  
  # add category: dem
  df <- df %>% 
    mutate(CAT = "dem") %>%
    relocate(CAT, .after = "TYPE") 
  
  # add sheet
  df <- df %>%
    mutate(SHEET = case_when(str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院内")~ "outpt_inpr",
                             str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院外")~ "outpt_outpr",
                             str_detect(SHEET_jp, "入院") ~ "inpt")) %>%
    relocate(SHEET, .after = "CAT")

  # add sheet
  df <- df %>% select(!FILE_ori)

   
  # fill empty cells in CLASS columns
  df <- df %>%
    tidyr::fill(starts_with("CLASS_"), .direction = "down")
  
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # create function for getting year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow = 1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  # get df for year
  df_year <- get_year(xlsx_path)
    
  df <- df %>% left_join(df_year, by = join_by(FILE))
  
  # convert everything to character for now
  df <- df %>% mutate(across(everything(), as.character))
  
  return(df)

  }
```


```{r}
# for each folider, read the first two files, parse , combine and save
# x is the overall folder name (oral ext inj)
# y is the individual folder

save_df_dem_2 <- function(x, y){
  xlsx <- list.files(paste0("../xlsx/", x, "/", y))
  
  xlsx <- xlsx[3:10]
  
    from <- paste0("../xlsx/", x, "/", y, "/", xlsx)
  
  df <- map(from, get_data_dem_2) %>% list_rbind()
  
  saveRDS(df, paste0("../rds/", x, "/", "dem/", "df_", x, "_", y, "_2"))
}
```


```{r}
# save file 3 and 10
for (i in 1:length(folder_oral_dem)){
  save_df_dem_2("oral", folder_oral_dem[i])
  print(paste0(folder_oral_dem[i], "_2", " completed"))
}
```



```{r}
df_ex <- readRDS("../rds/oral/dem/df_oral_inpt_dem_1")

df_ex_2 <- readRDS("../rds/oral/dem/df_oral_inpt_dem_2")
```

```{r}
df_ex <- readRDS("../rds/oral/dem/df_oral_outpt_inpr_dem_1")

df_ex_2 <- readRDS("../rds/oral/dem/df_oral_outpt_inpr_dem_2")
```


```{r}
setdiff(colnames(df_ex), colnames(df_ex_2))
```


```{r}
setdiff(colnames(df_ex_2), colnames(df_ex))
```

