---
title: "OTC-like drugs"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(readxl)
library(openxlsx)
```


```{r}
# make df folder

dir.create("../df/combine", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/combine/dem", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../df/combine/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
file_rbind <- list.files("../df/rbind") %>% str_subset("oral|inj|ext") %>% str_remove("\\.RDS")

file_rbind
```

```{r}
path_rbind <- paste0("../df/rbind/", file_rbind, ".RDS")
```


```{r}
for (i in 1:length(file_rbind)){
  assign(file_rbind[i], readRDS(path_rbind[i]))
}
```

```{r}
df_drug <- readRDS("../rds/drug/df_drug")
```

```{r}
df_drug %>% distinct(COST_code, ING, DOSE) %>% count(COST_code, ING, DOSE) %>%
  group_by(COST_code) %>%
  filter(n()>1) %>% View() 
```

```{r}
df_drug_uni <- df_drug %>% distinct(COST_code, ING, DOSE, .keep_all = TRUE)  %>%
  group_by(COST_code) %>%
  slice_head(n = 1) %>%
  ungroup()
```

```{r}
df_drug_uni %>% count(GENERIC, ORIGINAL)
```

```{r}
df_drug_uni %>% filter(ORIGINAL == "準先発品")
```

```{r}
df_drug_uni %>% filter(GENERIC == "★")
```


```{r}
df_drug_uni %>%
  filter(is.na(GENERIC) & is.na(ORIGINAL))
```


```{r}
df_drug_uni <- df_drug_uni %>%
  rename(DOSE_drug = "DOSE") %>%
  mutate(GEN_drug = case_when(!is.na(ORIGINAL) ~ "1",
                             .default = "0"))
```


```{r}
setdiff(colnames(df_oral_dem_2), colnames(df_oral_dem_1))

setdiff(colnames(df_oral_prf_2), colnames(df_oral_prf_1))
```
```{r}
setdiff(colnames(df_inj_dem_2), colnames(df_inj_dem_1))

setdiff(colnames(df_inj_prf_2), colnames(df_inj_prf_1))
```


```{r}
setdiff(colnames(df_ext_dem_2), colnames(df_ext_dem_1))

setdiff(colnames(df_ext_prf_2), colnames(df_ext_prf_1))
```

```{r}
colnames(df_drug_uni)
```
```{r}
df_oral_dem_2 %>%
    distinct(COST_code, UNIT) %>%
  group_by(COST_code) %>%
  filter(n()>1)
```

```{r}
df_oral_dem_2 %>%
  filter(COST_code == "7229001S1038") %>%
  count(UNIT)
```


```{r}
bind_df <- function(x, y){
  
  # first row update from y
  
  y_for_update <- y %>%
    select(COST_code, UNIT) %>%
    group_by(COST_code) %>%
    slice_head(n = 1)
  
  x_update <- x %>%
    left_join(y_for_update,
              by = join_by(COST_code))
  
  # row bind x and y
  
  df <- x_update %>%
    bind_rows(y) %>%
    rename(UNIT_ndb = "UNIT") %>%
    left_join(df_drug_uni %>% 
                select(COST_code, ING, DOSE_drug, GENERIC, ORIGINAL, ORI_w_GEN, GEN_drug),
              by = join_by(COST_code))
}
```

```{r}
df_oral_dem <- bind_df(df_oral_dem_1, df_oral_dem_2) 
```

```{r}
df_oral_dem %>% count(UNIT_ndb)
```

```{r}
df_oral_dem %>% count(DOSE_drug)
```


```{r}
parse_df <- function(x, y){
  
  file_all <- list.files("../df/rbind") %>%
    str_subset("oral|inj|ext") 
  
  path_all <- paste0("../df/rbind/", file_all )
  
  path_1 <- path_all %>% str_subset(x) %>% str_subset(y) %>% str_subset("1")
  
  path_2 <- path_all %>% str_subset(x) %>% str_subset(y) %>% str_subset("2")
  
  
  df_1 <- readRDS(path_1)
  
  df_2 <- readRDS(path_2)
  
  df <- bind_df(df_1, df_2) %>%
    mutate(across(c(COST_per, TOTAL), ~ str_replace_all(.x, "-", "0"))) %>%
    mutate(across(c(COST_per, TOTAL), ~ as.numeric(.x))) %>%
    mutate(YEAR = as.numeric(YEAR_str))
  

  saveRDS(df, paste0("../df/combine/", y,  "/df_", x, "_", y, ".RDS"))
}
```


```{r}
drug_type <- c(rep("oral", 2),
               rep("inj", 2),
               rep("ext", 2))

drug_type 

data_type <- rep(c("dem", "prf"), 3)

data_type
```

```{r}
# use for loop

for (i in 1:length(drug_type)){
  parse_df(drug_type[i], data_type[i])
  print(paste0("df_", drug_type[i], "_",  data_type[i], " completed"))
}
```

