---
title: "OTC-like drugs"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(stringi)
library(ggh4x)

library(cowplot)
library(patchwork)
library(ggtext)
library(ggrepel)
```


```{r}
# make df folder

dir.create("../df/filter", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/filter/dem", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../df/filter/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
file_dem <- list.files("../df/clean/dem") %>% str_remove("\\.RDS")

file_dem

path_dem <- paste0("../df/clean/dem/", file_dem , ".RDS")
```

```{r}
file_prf <- list.files("../df/clean/prf") %>% str_remove("\\.RDS")

file_prf

path_prf <- paste0("../df/clean/prf/", file_prf , ".RDS")
```

```{r}
file_all <- c(file_dem, file_prf)

path_all<- c(path_dem, path_prf)
```


```{r}
for (i in 1:length(file_all)){
  assign(file_all[i], readRDS(path_all[i]))
}
```

```{r}
df_otc <- readRDS("../rds/otc/df_otc.RDS")
```


# filter OTC

# ext data

```{r}
ing_otc <- df_otc %>% pull(ING_otc)
```

```{r}
df_all_dem <- df_oral_dem %>%
  bind_rows(df_ext_dem)
```


```{r}
ing_ndb <- df_all_dem %>%
  distinct(ING) %>%
  pull(ING)
```

```{r}
setdiff(ing_otc, ing_ndb)
```

```{r}
df_all_dem %>%
  filter(str_detect(ING, "カルボシステイン|クロラムフェニコール|サリチル酸メチル|フラジオマイシン"))　%>%
  count(ING) %>% View()

# Ｌ－カルボシステイン
# カルボシステイン
```

```{r}
df_all_dem %>%
  filter(TYPE == "oral" & ING == "デキサメタゾン") %>%
  distinct(CLASS_code, DRUG_code, DRUG_name)
```
```{r}
df_all_dem %>%
  filter(! (TYPE == "oral" & ING == "デキサメタゾン")) %>%
  distinct(CLASS_code, DRUG_code, DRUG_name)
```


```{r}
filter_otc <- c(ing_otc,
                "Ｌ－カルボシステイン",
                "カルボシステイン")
```

```{r}
df_all_dem %>%
  filter(ING %in% c("Ｌ－カルボシステイン",
                "カルボシステイン")) %>%
  count(DRUG_name)
```

```{r}
# 抗生物質　抗ウイルス薬　抗真菌薬

otc_amb <- c("抗生物質", "抗ウイルス薬",　"抗真菌薬") %>% paste0(collapse = "|")

ing_amb <- df_otc %>% filter(str_detect(CLASS_otc, otc_amb)) %>% pull(ING_otc)

ing_amb 
```
```{r}
df_all_dem %>%
  filter(ING %in% ing_amb ) %>%
  distinct(TYPE, ING)
```



```{r}
df_all_dem %>%
  filter(ING %in% filter_otc) %>%
  filter(!str_detect(DRUG_name, "フルタイド"))　%>%
  count(ING, DOSE_drug)
```

```{r}
  filter_otc <- c(ing_otc,
                "Ｌ－カルボシステイン",
                "カルボシステイン")
```


```{r}
df_all_dem %>%
  filter(ING %in%   filter_otc) %>%
  distinct(CLASS_name)
```

```{r}
df_all_dem %>%
  filter(ING %in%   filter_otc) %>%
  filter(CLASS_name == "眼科用剤") %>%
  distinct(TYPE, ING)

```


```{r}
df_all_dem %>%
  filter(ING %in%   filter_otc) %>%
  filter(CLASS_name == "眼科用剤") %>%
  filter(ING %in% c("アシクロビル", "クロラムフェニコール"))
```


```{r}

df_all_dem %>%
  filter(ING %in% filter_otc) %>%
  filter(str_detect(CLASS_name, "主としてグラム陽性・陰性菌，リケッチア")) %>%
  distinct(ING, TYPE)
```
```{r}

df_all_dem %>%
  filter(ING %in% filter_otc) %>%
  filter(str_detect(CLASS_name, "その他の化学療法剤")) %>%
  distinct(ING, TYPE)
```


```{r}
df_all_dem %>%
  filter(ING %in% filter_otc) %>%
  filter(!str_detect(DRUG_name, "フルタイド"))　%>%
  count(ING, DOSE_drug) %>%
  mutate(DOSE_h = stri_trans_general(DOSE_drug, "fullwidth-halfwidth")) %>%
    mutate(DOSE_h = str_remove(DOSE_h, "\\([^\\)]+\\)")) %>%
    mutate(DOSE_wt = case_when(str_detect(DOSE_h, "mg") ~ str_extract(DOSE_h, ".+(?=mg)"),
                           str_detect(DOSE_h, "μg") ~ str_extract(DOSE_h, ".+(?=μg)"),
                           str_detect(DOSE_h, "[:digit:]+g") ~ str_extract(DOSE_h, "[:digit:]+(?=g)"),
                            str_detect(DOSE_h, "単位") ~ str_extract(DOSE_h, ".+(?=単位)"),
                           DOSE_h == "1ｷｯﾄ" ~ "1kit")) %>%
  mutate(DOSE_unit = case_when(str_detect(DOSE_h, "mg") ~ "mg",
                               str_detect(DOSE_h, "μg") ~ "μg",
                               str_detect(DOSE_h, "[:digit:]+g") ~ "g",
                               str_detect(DOSE_h, "単位") ~ "unit",
                               .default = NA))
```


```{r}
df_unit <- df_all_dem %>%
  filter(ING %in% filter_otc) %>%
  filter(!str_detect(DRUG_name, "フルタイド"))　%>%
  count(ING, TYPE, DOSE_drug) %>%
  mutate(DOSE_h = stri_trans_general(DOSE_drug, "fullwidth-halfwidth")) %>%
    mutate(DOSE_h = str_remove(DOSE_h, "\\([^\\)]+\\)")) %>%
    mutate(DOSE_wt = case_when(str_detect(DOSE_h, "mg") ~ str_extract(DOSE_h, ".+(?=mg)"),
                           str_detect(DOSE_h, "μg") ~ str_extract(DOSE_h, ".+(?=μg)"),
                           str_detect(DOSE_h, "[:digit:]+g") ~ str_extract(DOSE_h, "[:digit:]+(?=g)"),
                            str_detect(DOSE_h, "単位") ~ str_extract(DOSE_h, ".+(?=単位)"),
                           DOSE_h == "1ｷｯﾄ" ~ "1kit")) %>%
  mutate(DOSE_g = case_when(str_detect(DOSE_h, "mg") ~ "mg",
                               str_detect(DOSE_h, "μg") ~ "μg",
                               str_detect(DOSE_h, "[:digit:]+g") ~ "g",
                            .default = NA)) %>%
  mutate(DOSE_pct = case_when(str_detect(DOSE_h, "\\%") ~ str_extract(DOSE_h, "[[:digit:]|\\.]+(?=\\%)"),
                              .default = NA)) %>%
  
  mutate(DOSE_vol = case_when(str_detect(DOSE_h, "mL") ~ str_extract(DOSE_h, "[[:digit:]|\\.]+(?=mL)"),
                              .default = NA)) %>%
  
  mutate(DOSE_ml = case_when(str_detect(DOSE_h, "mL") ~ "mL",
                             .default = NA)) %>%
  
  mutate(DOSE_sheet = case_when(str_detect(DOSE_drug, "枚") ~ "sheet",
                               .default = NA)) 
# zero
```

```{r}
add_unit <- function(x){
  
  x %>%
   mutate(DOSE_h = stri_trans_general(DOSE_drug, "fullwidth-halfwidth")) %>%
    mutate(DOSE_h = str_remove(DOSE_h, "\\([^\\)]+\\)")) %>%
    mutate(DOSE_wt = case_when(str_detect(DOSE_h, "mg") ~ str_extract(DOSE_h, ".+(?=mg)"),
                           str_detect(DOSE_h, "μg") ~ str_extract(DOSE_h, ".+(?=μg)"),
                           str_detect(DOSE_h, "[:digit:]+g") ~ str_extract(DOSE_h, "[:digit:]+(?=g)"),
                            str_detect(DOSE_h, "単位") ~ str_extract(DOSE_h, ".+(?=単位)"),
                           DOSE_h == "1ｷｯﾄ" ~ "1kit")) %>%
  mutate(DOSE_g = case_when(str_detect(DOSE_h, "mg") ~ "mg",
                               str_detect(DOSE_h, "μg") ~ "μg",
                               str_detect(DOSE_h, "[:digit:]+g") ~ "g",
                            .default = NA)) %>%
  mutate(DOSE_pct = case_when(str_detect(DOSE_h, "\\%") ~ str_extract(DOSE_h, "[[:digit:]|\\.]+(?=\\%)"),
                              .default = NA)) %>%
  
  mutate(DOSE_vol = case_when(str_detect(DOSE_h, "mL") ~ str_extract(DOSE_h, "[[:digit:]|\\.]+(?=mL)"),
                              .default = NA)) %>%
  
  mutate(DOSE_ml = case_when(str_detect(DOSE_h, "mL") ~ "mL",
                             .default = NA)) %>%
  
  mutate(DOSE_sheet = case_when(str_detect(DOSE_drug, "枚") ~ "sheet",
                               .default = NA)) 
}
```

```{r}
# クロラムフェニコール　内服　除外
# テルビナフィン塩酸塩	内服　除外
# アシクロビル			内服　除外

#　フルタイド　外用扱い　除外
# デキサメタゾン　内服　除外

# "眼科用剤"
# "アシクロビル", "クロラムフェニコール"
```


```{r}
# path oral

path_dem <- path_all[ !str_detect(path_all, "inj")]

path_dem

```


```{r}
for (i in 1:length(path_dem)){
  
  ing_otc <- df_otc %>% pull(ING_otc)
  
  filter_otc <- c(ing_otc,
                "Ｌ－カルボシステイン",
                "カルボシステイン")
  
  path <- path_dem[i]
  
  path_save <- path %>% str_replace("clean", "filter")
  
  df <- readRDS(path)
  
  df <- df %>%
    filter(ING %in% filter_otc) %>%
    filter(!str_detect(DRUG_name, "フルタイド"))　%>%
    filter(! (TYPE == "oral" & ING == "デキサメタゾン")) %>%
    filter(! (TYPE == "oral" & ING %in% c("クロラムフェニコール",
                                          "テルビナフィン塩酸塩",
                                          "アシクロビル"))) %>%
    filter(! (CLASS_name == "眼科用剤" & ING %in% c("アシクロビル",
                                                "クロラムフェニコール", 
                                                "デキサメタゾン"))) %>%
    add_unit() %>%
    mutate(TOTAL = str_replace(TOTAL, "-", "0")) %>%
    mutate(TOTAL = as.numeric(TOTAL))

  saveRDS(df, path_save)
  
}
```

# end
