---
title: "All drugs"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(stringi)
library(ggh4x)

library(cowplot)
library(patchwork)
library(ggtext)
library(ggrepel)

library(ggh4x)
library(rkt)
```

```{r}
options(knitr.df_print = rmarkdown::paged_table)
```


```{r}
# make df folder

dir.create("../df/format", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/format/dem", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../df/format/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
file_dem <- list.files("../df/filter/dem") %>% str_remove("\\.RDS")

file_dem

path_dem <- paste0("../df/filter/dem/", file_dem , ".RDS")
```

```{r}
file_prf <- list.files("../df/filter/prf") %>% str_remove("\\.RDS")

file_prf

path_prf <- paste0("../df/filter/prf/", file_prf , ".RDS")
```

```{r}
file_all <- c(file_dem, file_prf)

path_all <- c(path_dem, path_prf)
```

```{r}
df_1 <- readRDS(path_all[1])
```


```{r}
list_df <- purrr::map(path_dem, function(x){
  
  df <- readRDS(x) %>%
    pivot_longer(cols = c(starts_with("M_"), starts_with("F_")),
              names_to = "SEX_AGE",
              values_to = "VALUE")

  df <- df  %>%
    mutate(SEX = str_extract(SEX_AGE, "^M|^F")) %>%
    mutate(AGE = str_remove(SEX_AGE, "^M_|^F_"))
  
  df <- df  %>%
    mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
    mutate(SEX = factor(SEX, levels = c("Male", "Female")))
  
  levels_age <- df %>% distinct(AGE) %>%
    mutate(AGE = str_replace_all(AGE, "_", "–")) %>%
    pull(AGE)
  
  df <- df  %>%
      mutate(AGE = str_replace(AGE, "_", "–")) %>%
    mutate(AGE = fct_other(AGE,
                         keep = as.character(levels_age[1:18]),
                         other_level = "90–"))
  
  
#   df <- df %>% 
#  mutate(AGE = str_replace(AGE, "_", "–")) %>%
#  mutate(AGE = factor(AGE, levels = levels_age))
  
  df <- df %>%
    mutate(across(c(TOTAL, VALUE), ~ str_replace(.x, "-", "0"))) %>%
    mutate(across(c(TOTAL, VALUE), ~ as.numeric(.x))) %>%
    mutate(across(c(TOTAL, VALUE), ~ replace_na(.x, 0)))
  
  return(df)
  
})
```


```{r}
for (i in 1:length(file_dem)){
  assign(file_dem[i], list_df[[i]])
}
```

```{r}
df_otc_dem <- df_oral_dem %>%
  bind_rows(df_ext_dem)
```

```{r}
pal_tab10 <- c("#1f77b4",
               "#ff7f0e",
               "#2ca02c",
               "#d62728",
               "#9467bd",
               "#17becf",
               "#e377c2",
               "#bcbd22",
               "#8c564b" )
  
  # tab:gray : #7f7f7f
```




```{r}
df_otc_dem %>%
  distinct(AGE) %>% pull(AGE)
```


```{r}
age_start <- seq(0, 90, 5)

age_end <- c(seq(4, 89, 5), "")

levels_age <- paste0(age_start, "–", age_end)

levels_age
```


```{r}
 df_otc_dem <- df_otc_dem %>%
  mutate(AGE = factor(AGE, levels_age))
```

```{r}
# Ｌ－カルボシステイン

df_otc_dem <- df_otc_dem %>%
  mutate(ING = str_remove(ING, "Ｌ－"))
```

```{r}
 df_otc_dem %>%
  distinct(SHEET)
```

```{r}
df_otc_age_1 <- df_otc_dem %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
  bind_rows(df_otc_dem %>%
              group_by(YEAR, AGE) %>%
              summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
              mutate(SEX = "All")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  mutate(CAT = "All")
```

```{r}
df_otc_age_2 <- df_otc_dem %>%
  filter(TYPE == "oral") %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
  bind_rows(df_otc_dem %>%
                filter(TYPE == "oral") %>%
              group_by(YEAR, AGE) %>%
              summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
              mutate(SEX = "All")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  mutate(CAT = "Oral")
```


```{r}
df_otc_age_3 <- df_otc_dem %>%
  filter(TYPE == "ext") %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
  bind_rows(df_otc_dem %>%
                filter(TYPE == "ext") %>%
              group_by(YEAR, AGE) %>%
              summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
              mutate(SEX = "All")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  mutate(CAT = "Topical")
```

```{r}
df_otc_age <- df_otc_age_1 %>%
  bind_rows(df_otc_age_2) %>%
  bind_rows(df_otc_age_3) %>%
  mutate(CAT = factor(CAT, levels = c("All", "Oral", "Topical"))) %>%
  ungroup()
```

```{r}
label_otc_age <- df_otc_age %>%
  distinct(SEX, CAT) %>%
  mutate(LABEL = case_when(SEX =="All"  ~ CAT,
                           .default = NA)) %>%
    mutate(x = case_when(SEX =="All"  ~ 2,
                           .default = NA)) %>%
    mutate(y = case_when(SEX =="All"  ~ 30,
                           .default = NA)) 

label_otc_age
```



```{r}
df_y_scale <- df_otc_age %>%
  filter(SEX == "All") %>%
  group_by(CAT) %>%
  summarise(MAX = max(SUM)) %>%
  mutate(YMAX = case_when(MAX > 30 ~ 40,
                          MAX > 15 ~ 20)) %>%
  mutate(YRAN = case_when(YMAX %in% c(20, 40)~ 4)) %>%
  mutate(YBRK = YMAX/YRAN)

df_y_scale
```


```{r}
scale_otc_age <- list(
  CAT == "All" ~ scale_y_continuous(limits =c(0, 40),
                                         breaks = seq(0, 40, 10)),
  CAT == "Oral" ~ scale_y_continuous(limits =c(0, 20),
                                         breaks = seq(0, 20, 5)),
  CAT == "Topical" ~ scale_y_continuous(limits =c(0, 20),
                                         breaks = seq(0, 20, 5))
    )
```

```{r}
levels_otc <- c("All", "Oral", "Topical") 
```

```{r}
labels_age <- df_otc_age %>% distinct(AGE) %>%
  arrange(AGE) %>%
  mutate(AGE = as.character(AGE)) %>%
  mutate(AGE = case_when(str_detect(AGE, "^5\\–|^[:digit:]5") ~ "",
                         .default = AGE)) %>%
  pull(AGE)

labels_age
```


```{r}
list_p1 <- purrr::map(levels_otc , function(cat){
  
  ymax <- df_y_scale %>% filter(CAT == cat) %>% pull(YMAX)
  ybrk <- df_y_scale %>% filter(CAT == cat) %>% pull(YBRK)
  
  df_otc_age %>%
    filter(SEX == "All" & CAT == cat) %>%
    mutate(YEAR = as.factor(YEAR)) %>%
    ggplot(aes( AGE, SUM, group = YEAR, colour = YEAR )) +
  geom_line(linewidth = 0.3)+
  scale_color_manual(values = pals::kovesi.rainbow(n = 10),
                     name = "Year")+
 #   scale_x_discrete(labels = labels_age)+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk)) +

  guides(color = guide_legend(nrow = 1,
                              override.aes = list(linewidth = 0.5) ) )+
  labs(title = cat,
       x = "Age",
       y = "Cost (×10<sup>9</sup> JPY)")+
  theme_classic()+
  theme(plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, vjust = 0.5),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 8, colour = "black", face = "bold"),
         strip.text.y.left = element_text(size = 8, colour = "black", face = "bold", angle = 90),
        
          axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        
          axis.text.x = element_text(size = 8, colour = "black", angle = 90, hjust = 1, vjust = 0.5),
         axis.text.y = element_markdown(size = 8, colour = "black"),
          axis.line = element_line(linewidth = 0.3, colour = "black"),
          axis.ticks = element_line(linewidth = 0.3, colour = "black"),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
        #  legend.key.height = unit(5, "mm"),
        legend.position = "right",
       legend.direction = "horizontal",
          plot.margin = margin(1, 1, 1, 1, "mm"))
})


```

```{r}
for (i in 1:length(list_p1 )){
  print(list_p1[[i]])
}
```


```{r}
p_leg <- list_p1[[1]] %>% get_legend() %>% wrap_elements() 
```


# top oral drugs


```{r}
ing_top_oral <- df_otc_dem %>%
  filter(TYPE == "oral") %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR,ING) %>%
  summarise(SUM = sum(TOTAL * COST_per)) %>%
  
  group_by(ING) %>%
  slice_max(SUM, n = 1) %>%
  ungroup() %>%
  
  slice_max(SUM, n = 9) %>%
  
  arrange(desc(SUM)) %>%
  pull(ING) %>%
  unique()

ing_top_oral
```

```{r}
convert_oral <- function(x){
  if (x == "フェキソフェナジン塩酸塩"){
    return("Fexofenadine hydrochloride")
  }
  
  else if (x == "カルボシステイン"){
    return("Carbocisteine")
  }
  
  else if (x == "ベポタスチンベシル酸塩")
    return("Bepotastine besilate")
  
  else if (x == "ロキソプロフェンナトリウム水和物"){
    return("Loxoprofen sodium hydrate")
  }
  
  else if (x == "酸化マグネシウム"){
    return("Magnesium oxide")
  }
  
  else if (x == "エピナスチン塩酸塩"){
    return("Epinastine hydrochloride")
  }
  
    else if (x == "ロラタジン"){
    return("Loratadine")
  }

    else if (x == "フェキソフェナジン塩酸塩・塩酸プソイドエフェドリン"){
    return("Fexofenadine hydrochloride/\nPseudoephedrine hydrochloride")
  }
  
    
  else if (x == "ピコスルファートナトリウム水和物"){
    return("Sodium picosulfate hydrate")
  }
  
  else {
    return("Others")
  }
}

convert_oral <- Vectorize(convert_oral)
```

```{r}
levels_oral <- convert_oral(ing_top_oral)

levels_oral
```



```{r}
df_otc_oral <- df_otc_dem %>%
  filter(TYPE == "oral" & ING %in% ing_top_oral[1:9]) %>%
  group_by(YEAR,ING, SEX, AGE) %>%
  summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
  
  bind_rows(df_otc_dem %>%
              filter(TYPE == "oral" & ING %in% ing_top_oral[1:9]) %>%
              group_by(YEAR, ING, AGE) %>%
              summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
              mutate(SEX = "All")) %>%
  
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  
  mutate(ING_en = convert_oral(ING) ) %>%
  mutate(ING_en = factor(ING_en, levels = levels_oral[1:9])) %>%
  ungroup()
```




```{r}
df_y_oral <- df_otc_oral %>%
  group_by(ING_en) %>%
  summarise(MAX = max(SUM)) %>%
  arrange(desc(MAX))
  

df_y_oral
```

```{r}
df_y_oral <- df_y_oral %>%
  mutate(YMAX = case_when(MAX > 4 ~ 5,
                          MAX > 3 ~ 4,
                          MAX > 2 ~ 2.5,
                          MAX > 1.5 ~ 2,
                          MAX > 0.8 ~ 1,
                          MAX > 0.5 ~ 0.6)) %>%
  mutate(YRAN = case_when(YMAX %in% c(0.6) ~ 3,
                          YMAX %in% c( 2, 4) ~ 4,
                          YMAX %in% c(1, 2.5, 5) ~ 5)) %>%
  mutate(YBRK = YMAX/YRAN)

df_y_oral
```

```{r}
df_y_oral <- df_y_oral %>% mutate(SEX ="All") %>%
  bind_rows(df_y_oral %>% mutate(SEX ="Male")) %>%
  bind_rows(df_y_oral %>% mutate(SEX = "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  arrange(ING_en, SEX) %>%
  mutate(ID = paste0(ING_en, "_", SEX)) 

df_y_oral
```

```{r}
levels_y_oral <- df_y_oral %>% pull(ID)

df_y_oral <- df_y_oral %>%
  mutate(ID = factor(ID, levels = levels_y_oral))
```


```{r}
y_oral_split <- split(df_y_oral,
                    df_y_oral$ID)
```

```{r}
y_oral_split[[1]]
```

```{r}
y_scales <- lapply(y_oral_split, 
                     function(x) {
  scale_y_continuous(limits = c(0, x$YMAX),
                     breaks = seq(0, x$YMAX, x$YBRK),
                     labels = scales::number_format(accuracy = 0.1))
})
```

```{r}
df_y_oral <- df_y_oral %>%
  mutate(x = (1+18)/2,
         hjust = 0.5,
         vjust = 0.5,
         label = SEX)
```


```{r}
labels_age <- df_otc_oral %>% distinct(AGE) %>%
  arrange(AGE) %>%
  mutate(AGE = as.character(AGE)) %>%
  mutate(AGE = case_when(str_detect(AGE, "^5\\–|^[:digit:]5") ~ "",
                         .default = AGE)) %>%
  pull(AGE)

labels_age
```


```{r}
list_p2 <- purrr::map(levels_oral, function(otc){
  
  ymax <- df_y_oral %>% filter(SEX == "All" & ING_en == otc) %>% pull(YMAX)
  ybrk <- df_y_oral %>% filter(SEX == "All" & ING_en == otc) %>% pull(YBRK)
  
  df_otc_oral %>%
    mutate(YEAR = as.factor(YEAR)) %>%
    filter(SEX == "All" & ING_en == otc) %>%
    ggplot(aes(AGE, SUM, group = YEAR, colour = YEAR))+
    geom_line(linewidth = 0.3)+
    guides(color = guide_legend(nrow = 1,
                                override.aes = list(linewidth = 0.5) ) )+
 #   scale_x_discrete(labels = labels_age)+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk)) +
    
    scale_colour_manual(values = pals::kovesi.rainbow(n = 10),
                        name = "Year")+
  labs(title = otc,
       x = "Age",
       y = "Cost (×10<sup>9</sup> JPY)")+
  theme_classic()+
    theme(plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, vjust = 0.5),

          axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
                  axis.text.x = element_markdown(size = 8, colour = "black",angle = 90, hjust = 1, vjust = 0.5),
        
          axis.text.y = element_text(size = 8, colour = "black"),
          axis.line = element_line(linewidth = 0.3, colour = "black"),
          axis.ticks = element_line(linewidth = 0.3, colour = "black"),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
        #  legend.key.height = unit(5, "mm"),
        legend.position = "right",
       legend.direction = "horizontal",
        plot.margin = margin(1, 1, 1, 1, "mm"))
  
})
```

```{r}
for (i in 1:length(list_p2)){
  print(list_p2[[i]])
  }
```


# top Topical


```{r}
ing_top_ext <- df_otc_dem %>%
    filter(TYPE == "ext") %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR,ING) %>%
  summarise(SUM = sum(TOTAL * COST_per)) %>%

  group_by(ING) %>%
  slice_max(SUM, n = 1) %>%
  ungroup() %>%
  
  slice_max(SUM, n = 9) %>%
  
  arrange(desc(SUM)) %>%
  pull(ING) %>%
  unique()

ing_top_ext
```

```{r}
df_otc_dem %>%
  filter(ING == "モメタゾンフランカルボン酸エステル水和物") %>%
  distinct(DRUG_name, ING)
```


```{r}
convert_ext <- function(x){
  if (x == "ヘパリン類似物質"){
    return("Heparinoid")
  }
  
  else if (x == "ロキソプロフェンナトリウム水和物"){
    return("Loxoprofen sodium hydrate")
  }
  
    else if (x == "エピナスチン塩酸塩"){
    return("Epinastine hydrochloride")
  }
  
  else if (x == "ジクロフェナクナトリウム"){
    return("Diclofenac sodium")
  }
  
  else if (x == "フェルビナク"){
    return("Felbinac")
  }
  
  else if (x == "モメタゾンフランカルボン酸エステル水和物"){
    return("Mometasone furoate hydrate")
  }
  
  else if (x == "フルチカゾンプロピオン酸エステル"){
    return("Fluticasone propionate")
  }
  
  else if (x == "白色ワセリン"){
    return("White petrolatum")
  }
  
  # else if (x == "ヒドロコルチゾン酪酸エステル"){
  #  return("Hydrocortisone butyrate")
  #  }
  
  else if (x == "インドメタシン"){
    return("Indomethacin")
      }
  
  else {
    return("Others")
  }
}

convert_ext <- Vectorize(convert_ext)
```

```{r}
levels_ext <- convert_ext(ing_top_ext)

levels_ext
```


```{r}
df_otc_ext <- df_otc_dem %>%
  filter(TYPE == "ext" & ING %in% ing_top_ext[1:9]) %>%
  group_by(YEAR,ING, SEX, AGE) %>%
  summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
  
  bind_rows(df_otc_dem %>%
              filter(TYPE == "ext" & ING %in% ing_top_ext[1:9]) %>%
              group_by(YEAR, ING, AGE) %>%
              summarise(SUM = sum(VALUE * COST_per)/10^9) %>%
              mutate(SEX = "All")) %>%
  
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  
  mutate(ING_en = convert_ext(ING) ) %>%
  mutate(ING_en = factor(ING_en, levels = levels_ext[1:9])) %>%
  ungroup()
```
```{r}
df_otc_dem %>%
  filter(TYPE == "ext" & ING %in% ing_top_ext[1:9]) %>%
  distinct(DRUG_name, ING) %>% View()
```


```{r}
df_y_ext_all <- df_otc_ext %>%
  group_by(ING_en) %>%
  summarise(MAX = max(SUM)) %>%
  arrange(desc(MAX))
  

df_y_ext_all 
```

```{r}
df_y_ext <- df_y_ext_all %>%
  mutate(YMAX = case_when(MAX > 15 ~ 16,
                          MAX >8 ~ 10,
                          MAX > 4 ~ 5,
                          MAX > 1.5 ~ 2,
                          MAX > 0.6 ~ 0.8,
                          MAX > 0.5 ~ 0.6,
                          MAX > 0.4 ~ 0.5,
                          MAX > 0.3 ~ 0.4)) %>%
  mutate(YRAN = case_when(YMAX %in% c(0.6) ~ 3, 
                          YMAX %in% c(0.4,0.8, 1, 2, 4, 16) ~ 4,
                          YMAX %in% c(0.5, 2.5, 5, 10) ~ 5)) %>%
  mutate(YBRK = YMAX/YRAN)

df_y_ext
```

```{r}
df_y_ext <- df_y_ext%>% mutate(SEX ="All") %>%
  bind_rows(df_y_ext %>% mutate(SEX ="Male")) %>%
  bind_rows(df_y_ext %>% mutate(SEX = "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  arrange(ING_en, SEX) %>%
  mutate(ID = paste0(ING_en, "_", SEX)) 

df_y_ext
```

```{r}
levels_y_ext <- df_y_ext %>% pull(ID)

df_y_ext <- df_y_ext %>%
  mutate(ID = factor(ID, levels = levels_y_ext))
```


```{r}
y_ext_split <- split(df_y_ext,
                    df_y_ext$ID)
```

```{r}
y_ext_split[[1]]
```

```{r}
y_ext_scales <- lapply(y_ext_split, 
                     function(x) {
  scale_y_continuous(limits = c(0, x$YMAX),
                     breaks = seq(0, x$YMAX, x$YBRK),
                     labels = scales::number_format(accuracy = 0.1))
})
```

```{r}
df_y_ext <- df_y_ext %>%
  mutate(x = (1+18)/2,
         hjust = 0.5,
         vjust = 0.5,
         label = SEX)
```


```{r}
list_p3 <- purrr::map(levels_ext, function(otc){
  
  ymax <- df_y_ext %>% filter(SEX == "All" & ING_en == otc) %>% pull(YMAX)
  ybrk <- df_y_ext %>% filter(SEX == "All" & ING_en == otc) %>% pull(YBRK)
  
  df_otc_ext %>%
    mutate(YEAR = as.factor(YEAR)) %>%
    filter(SEX == "All" & ING_en == otc) %>%
    tidyr::complete(YEAR) %>%
    ggplot(aes(AGE, SUM, group = YEAR, colour = YEAR))+
    geom_line(linewidth = 0.3)+
    guides(color = guide_legend(nrow = 1,
                                override.aes = list(linewidth = 0.5) ) )+
 #   scale_x_discrete(labels = labels_age)+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk)) +
    
    scale_colour_manual(values = pals::kovesi.rainbow(n = 10),
                        name = "Year")+
  labs(title = otc,
       x = "Age",
       y = "Cost (×10<sup>9</sup> JPY)")+
  theme_classic()+
    theme(plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, vjust = 0.5),

          axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
                  axis.text.x = element_markdown(size = 8, colour = "black",angle = 90, hjust = 1, vjust = 0.5),
        
          axis.text.y = element_text(size = 8, colour = "black"),
          axis.line = element_line(linewidth = 0.3, colour = "black"),
          axis.ticks = element_line(linewidth = 0.3, colour = "black"),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
       #  legend.key.height = unit(5, "mm"),
        legend.position = "right",
       legend.direction = "horizontal",
        plot.margin = margin(1, 1, 1, 1, "mm"))
  
})
```

```{r}
for (i in 1:length(list_p3)){
  print(list_p3[[i]])
  }
```



```{r}
# p1

# remove x axis for 1, 3
# remove y axis for 2, 3

for (i in 1:length(list_p1)){
  
  if (i %in% 2:3){
  list_p1[[i]] <- list_p1[[i]] +
    theme(axis.title.y = element_blank())
  }
  else {
    list_p1[[i]] <- list_p1[[i]]
  }
}

for (i in 1:length(list_p1)){
  
  if (i %in% c(1, 3)){
  list_p1[[i]] <- list_p1[[i]] +
    theme(axis.title.x = element_blank())
  }
  else {
    list_p1[[i]] <- list_p1[[i]]
  }
}


for (i in 1:length(list_p1)){
  
  list_p1[[i]] <- list_p1[[i]] + 
    theme(legend.position = "none")
}

# plot margin zero

for (i in 1:length(list_p1)){
  
  list_p1[[i]] <- list_p1[[i]] +
    theme(plot.margin = margin(1, 1, 1, 1, "mm"))
}

```

```{r}
list_p1[[1]] <- list_p1[[1]]+
  labs(tag = "A")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
# p2

# remove x axis for 1:6
# remove y axis except for  1, 4, 7 

for (i in 1:length(list_p2)){
  
  if (i %in% 1:6){
  list_p2[[i]] <- list_p2[[i]] +
    theme(axis.text.x = element_blank())
  }
  else {
    list_p2[[i]] <- list_p2[[i]]
  }
}


for (i in 1:length(list_p2)){
  
  if (i %in% 8){
        list_p2[[i]] <- list_p2[[i]]
  }
  else {
      list_p2[[i]] <- list_p2[[i]] +
    theme(axis.title.x = element_blank())
  }
}


for (i in 1:length(list_p2)){
  
  if (i %in% c( 4)){
  list_p2[[i]] <- list_p2[[i]] 
  }
  else {
    list_p2[[i]] <- list_p2[[i]]+
    theme(axis.title.y = element_blank())
  }
}

for (i in 1:length(list_p2)){
  
  list_p2[[i]] <- list_p2[[i]] + 
    theme(legend.position = "none")
}

# plot margin zero

for (i in 1:length(list_p2)){
  
  list_p2[[i]] <- list_p2[[i]] +
    theme(plot.margin = margin(1, 1, 1, 1, "mm"))
}

```

```{r}
list_p2[[1]] <- list_p2[[1]]+
  labs(tag = "B")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
# p2

# remove x axis for 1:6
# remove y axis except for  1, 4, 7 

for (i in 1:length(list_p3)){
  
  if (i %in% 1:6){
  list_p3[[i]] <- list_p3[[i]] +
    theme(
          axis.text.x = element_blank())
  }
  else {
    list_p3[[i]] <- list_p3[[i]]
  }
}


for (i in 1:length(list_p3)){
  
  if (i %in% 8){
        list_p3[[i]] <- list_p3[[i]]
  }
  else {
     list_p3[[i]] <- list_p3[[i]] +
    theme(axis.title.x = element_blank())
  }
}


for (i in 1:length(list_p3)){
  
  if (i %in% c(4)){
  list_p3[[i]] <- list_p3[[i]] 
  }
  else {
    list_p3[[i]] <- list_p3[[i]]+
    theme(axis.title.y = element_blank())
  }
}



for (i in 1:length(list_p3)){
  
  list_p3[[i]] <- list_p3[[i]] + 
    theme(legend.position = "none")
}

# plot margin zero

for (i in 1:length(list_p3)){
  
  list_p3[[i]] <- list_p3[[i]] +
    theme(plot.margin = margin(1, 1, 1, 1, "mm"))
}

```

```{r}
list_p3[[1]] <- list_p3[[1]]+
  labs(tag = "C")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
# for each list, assign p1_x

list_p_all <- list(list_p1, list_p2, list_p3)
```

```{r}
for (i in 1:length(list_p_all)){
  
  num <- length(list_p_all[[i]])
  
  for (j in 1:num){
  
  assign(paste0("p", i, "_", j), list_p_all[[i]][[j]])
  
  }
}
```


```{r}
p123 <- p1_1 + p1_2 + p1_3 + 
  p2_1 + p2_2 + p2_3 + 
  p2_4 + p2_5 + p2_6 + 
  p2_7 + p2_8 + p2_9 + 
  p3_1 + p3_2 + p3_3 +
  p3_4 + p3_5 + p3_6 + 
  p3_7 + p3_8 + p3_9 +
  plot_layout(ncol = 3,
              guides = "collect")&
  theme(legend.position = "bottom",
        legend.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.spacing = unit(1, "mm"),
        legend.justification.bottom = c(1, 0.5))

ggsave("../figure/Fig2.pdf", p123, 
       width = 175, height = 235, units ="mm")
  
```

