---
title: "OTC-like drugs"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(stringi)
library(ggh4x)

library(cowplot)
library(patchwork)
library(ggtext)
library(ggrepel)

library(ggh4x)
library(rkt)
```

```{r}
options(knitr.df_print = rmarkdown::paged_table)
```


```{r}
file_name <- list.files("../plot", pattern = "list") %>% str_remove("\\.RDS")

file_name

path_name <- paste0("../plot/", file_name , ".RDS")
```


```{r}
for (i in 1:length(file_name)){
  assign(file_name[i], readRDS(path_name[i]))
}
```

```{r}
for (i in 1:length(list_p1)){
  print(list_p1[[i]])
}
```

```{r}
# remove x axis for 1, 3

for (i in 1:length(list_p1)){
  
  if (i %in% c(1, 3)){
  list_p1[[i]] <- list_p1[[i]] +
    theme(axis.title.x = element_blank())
  }
  else {
    list_p1[[i]] <- list_p1[[i]]
  }
}

# remove y axis for 2, 3

for (i in 1:length(list_p1)){
  
  if (i %in% 2:3){
  list_p1[[i]] <- list_p1[[i]] +
    theme(axis.title.y = element_blank(),
          axis.text.y = element_blank())
  }
  else {
    list_p1[[i]] <- list_p1[[i]]
  }
}

# plot margin zero

for (i in 1:length(list_p1)){
  
  list_p1[[i]] <- list_p1[[i]] +
    theme(plot.margin = margin(0, 1, 0, 1, "mm"))
}

```

```{r}
# add tag

list_p1[[1]] <- list_p1[[1]]+
  labs(tag = "A")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
for (i in 1:length(list_p2)){
  print(list_p2[[i]])
}
```

```{r}
p_leg <- list_p2[[i]] %>% get_legend() %>% wrap_elements()
```


```{r}
# remove x axis for 1, 3

# remove y axis for 2, 3

for (i in 1:length(list_p2)){
  
  if (i %in% 2:3){
  list_p2[[i]] <- list_p2[[i]] +
    theme(axis.title.y = element_blank())
  }
  else {
    list_p2[[i]] <- list_p2[[i]]
  }
}

for (i in 1:length(list_p2)){
  
  list_p2[[i]] <- list_p2[[i]] + 
    theme(legend.position = "none")
}

# plot margin zero

for (i in 1:length(list_p2)){
  
  list_p2[[i]] <- list_p2[[i]] +
    theme(plot.margin = margin(0, 1, 0, 1, "mm"))
}

```

```{r}
list_p2[[1]] <- list_p2[[1]]+
  labs(tag = "B")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
for (i in 1:length(list_p3)){
  print(list_p3[[i]])
}
```

```{r}

# remove y axis for 2, 3, 4

for (i in 1:length(list_p3)){
  
  if (i %in% 2:4){
  list_p3[[i]] <- list_p3[[i]] +
    theme(axis.title.y = element_blank())
  }
  else {
    list_p3[[i]] <- list_p3[[i]]
  }
}

for (i in 1:length(list_p3)){
  
  list_p3[[i]] <- list_p3[[i]] + 
    theme(legend.position = "none")
}


for (i in 1:length(list_p3)){
  
  list_p3[[i]] <- list_p3[[i]] +
    theme(plot.margin = margin(0, 1, 0, 1, "mm"))
}


```

```{r}
list_p3[[1]] <- list_p3[[1]]+
  labs(tag = "C")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```


```{r}
for (i in 1:length(list_p4)){
  print(list_p4[[i]])
}
```

```{r}

# remove y axis for 2, 3, 4

for (i in 1:length(list_p4)){
  
  if (i %in% 2:4){
  list_p4[[i]] <- list_p4[[i]] +
    theme(axis.title.y = element_blank())
  }
  else {
    list_p4[[i]] <- list_p4[[i]]
  }
}

for (i in 1:length(list_p4)){
  
  list_p4[[i]] <- list_p4[[i]] + 
    theme(legend.position = "none")
}


for (i in 1:length(list_p4)){
  
  list_p4[[i]] <- list_p4[[i]] +
    theme(plot.margin = margin(0, 1, 0, 1, "mm"))
}

```

```{r}
list_p4[[1]] <- list_p4[[1]]+
  labs(tag = "D")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))
```

```{r}
for (i in 1:length(list_p5)){
  
  if (i %in% 1){
  list_p5[[i]] <- list_p5[[i]] +
    theme(axis.title.x = element_blank(),
          plot.margin = margin(0, 0, 1, 0, unit = "mm"))
  }
  else {
    list_p5[[i]] <- list_p5[[i]] +
      theme(strip.text = element_blank(),
            plot.margin = margin(1, 0, 0, 0 ,unit = "mm"))
  }
}

```


```{r}
list_p5[[1]] <- list_p5[[1]]+
  labs(tag = "E")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_blank())
```

```{r}
# for each list, assign p1_x

list_p_all <- list(list_p1, list_p2, list_p3, list_p4, list_p5)
```

```{r}
for (i in 1:length(list_p_all)){
  
  num <- length(list_p_all[[i]])
  
  for (j in 1:num){
  
  assign(paste0("p", i, "_", j), list_p_all[[i]][[j]])
  
  }
}
```


```{r}
p1 <- p1_1 + p1_2 + p1_3 + p_leg +
  p2_1 + p2_2 + p2_3 +
  p3_1 + p3_2 + p3_3 + p3_4 +
  p4_1 + p4_2 + p4_3 + p4_4 +
  p5_1 +
  p5_2 +
  plot_layout(design = "
              ABCD
              EFGD
              HIJK
              LMNO
              PPPP
              QQQQ")

ggsave("../figure/Fig1.pdf", p1, 
       width = 175, height = 235, units ="mm")
  
```

```{r}
ggsave("../figure/Fig1_assemble.jpg", p1, 
       width = 175, height = 235, dpi = 300, units ="mm")
```

```{r}
ggsave("../figure/Fig1_assemble.tiff", p1, 
       width = 175, height = 235, dpi = 600, units ="mm",
       compression = "lzw")
```

