---
title: "Drugs"
output: html_document
date: "2026-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openxlsx)
library(readxl)
```

```{r}
dir.create("../rds/drug",
             showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


```{r}
list.files("../xlsx")
```

```{r}
list.files("../xlsx/drug")
```

```{r}
xlsx_name_inj <- list.files("../xlsx/drug/inj") 
```

```{r}
xlsx_path_inj <- paste0("../xlsx/drug/inj/", xlsx_name_inj)
```

```{r}
xlsx_path_inj
```


```{r}
# x is oral, inj, ext

parse_drug <- function(x){
  
  df <- read_excel(x, 
                   col_names = c("TYPE",
                                "COST_code",
                    "ING",
                    "DOSE",
                    "X_e",
                    "X_f",
                    "X_g",
                    "DRUG_name",
                    "COMPANY",
                    "GENERIC",
                    "ORIGINAL",
                    "ORI_w_GEN",
                    "COST_per",
                    "DEADLINE",
                    "NOTE"),
                   skip = 1) %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)[^\\/]+(?=\\.xls)")) %>%
    mutate(YEAR = str_extract(FILE, "(?<=tp)2[:digit:]{3}"))
}
```

```{r}
df_drug_name_inj <- map( xlsx_path_inj[2:length(xlsx_path_inj)], parse_drug) %>% list_rbind()
```
```{r}
df_drug_inj %>% count(FILE)
```

```{r}
saveRDS(df_drug_name_inj, "../rds/drug/df_drug_name_inj")
```





```{r}
df_name <- tibble(NAME = xlsx_name)
```

```{r}
df_drug_name <- df_name %>%
  mutate(ORDER = str_extract(NAME, "(?<=_)[:digit:]+(?=\\.xlsx)"))

df_drug_name
```

```{r}
df_drug_name <- df_drug_name %>% arrange(ORDER) %>%
  mutate(FILE = case_when(ORDER == "01" ~ "oral",
                          ORDER == "02" ~ "inj",
                          ORDER == "03" ~ "ext",
                          ORDER == "04" ~ "dent",
                          ORDER == "05" ~ "oth")) %>%
  mutate(PATH = paste0("../xlsx/drug/", NAME))

df_drug_name
```


```{r}
xlsx_name <- df_drug_name$NAME

xlsx_file <- df_drug_name$FILE

xlsx_path <- df_drug_name$PATH
```

```{r}
df_drug_oral <- read.xlsx(xlsx_path[1], startRow = 1,
                 fillMergedCells = FALSE) 
```


```{r}
df_drug_inj <- read.xlsx(xlsx_path[2], startRow = 1,
                 fillMergedCells = FALSE) 
```

```{r}
df_drug_ext <- read.xlsx(xlsx_path[3], startRow = 1,
                 fillMergedCells = FALSE) 
```


```{r}
df_drug_dent <- read.xlsx(xlsx_path[4], startRow = 1,
                 fillMergedCells = FALSE) 
```

```{r}
df_drug_oth <- read.xlsx(xlsx_path[5], startRow = 1,
                 fillMergedCells = FALSE) 
```

```{r}
df_drug_oth %>% filter(str_detect(成分名, "ベバシズマブ"))
```
```{r}
df_drug_oth %>% filter(str_detect(成分名, "トラスツズマブ"))
```

```{r}
df_drug_oth %>% filter(str_detect(品名, "オプジーボ"))
```

```{r}
df_drug_oth %>% filter(str_detect(品名, "フェントス"))
```

```{r}
colnames(df_drug_oral)
```


```{r}
get_df_drug_name_13 <- function(xlsx_path){
  df <- read.xlsx(xlsx_path, startRow = 1,
                 fillMergedCells = FALSE) 
  
  colnames(df) <- c("TYPE",
                    "COST_code",
                    "ING",
                    "DOSE",
                    "X5",
                    "X6",
                    "X7",
                    "DRUG_name",
                    "COMPANY",
                    "GENERIC",
                    "ORIGINAL",
                    "GEN_with_ORI",
                    "COST_per",
                    "DEADLINE",
                    "COMMENT")
  
  df <- df %>% mutate(GO = case_when(!is.na(ORIGINAL) ~ ORIGINAL,
                                     is.na(ORIGINAL) & !is.na(GENERIC) ~ GENERIC,
                                     .default = NA))
  
  return(df)
}
```

```{r}
df_1 <- get_df_drug_name_13(xlsx_path[1])
```

```{r}
list_drug_name <- map(xlsx_path[1:3], get_df_drug_name_13)
```

```{r}
to_drug_name <- paste0("../rds/drug/df_drug_name_", xlsx_file[1:3])
```

```{r}
# save ext, inj, oral

for (i in 1:length(to_drug_name)){
  saveRDS(list_drug_name[[i]], to_drug_name[i])
}
```

```{r}
df_drug_name_oth <- read.xlsx(xlsx_path[5], startRow = 1,
                 fillMergedCells = FALSE) 
```


```{r}
colnames(df_drug_name_oth)
```

```{r}
colnames(df_drug_name_oth) <- c("COST_code",
                                "ING",
                                "DRUG_name",
                                "INFO_gen",
                                "INDEX_date",
                                "LIMIT",
                                "COMMENT",
                                "EXCLUDE",
                                "CUTOFF")
```

```{r}
saveRDS(df_drug_name_oth, "../rds/drug/df_drug_name_oth")
```

# end of run


```{r}
colnames(df_drug_oth)[1:3] <- c("DRUG_code", "ING", "PRODUCT")
```

```{r}
df_drug_oth %>% select(any_of(c("DRUG_code", "ING", "PRODUCT"))) %>%
  saveRDS("../rds/drug/df_drug_oth")
```

# end





```{r}
get_df_drug <- function(xlsx_path){
  
  # read excel sheet
  df <- read.xlsx(xlsx_path, startRow = 1,
                 fillMergedCells = FALSE) 
  
  
  # clean colnames
  colnames(df)[1:8] <- c("CLASS_code", "CLASS_name",
                       "DRUG_code", "DRUG_name",
                       "COST_code", "COST_per",
                       "GEN", "TOTAL")

  start <- seq(0, 85, 5)
  end <- seq(4, 89, 5)
  
  range <- paste0(start, "_", end)
  range <- c(range, "90_")
  
  age_sex <- c(paste0("M_", range), paste0("F_", range))
  
  colnames(df)[9:46] <- age_sex
  
  # add file name
  df <- df %>% mutate(FILE_ori = xlsx_path) %>%
    mutate(FILE = str_extract(FILE_ori, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    relocate(FILE, .before = "CLASS_code")
  
  # add sheet name and type
  df <- df %>% mutate(SHEET_jp = sheet_name) %>%
    mutate(TYPE = case_when(str_detect(SHEET_jp, "内服")　~ "oral",
                            str_detect(SHEET_jp, "外用") ~ "ext",
                            str_detect(SHEET_jp, "注射") ~ "inj")) %>%
    relocate(TYPE, .after = "FILE")
    
  
  # add category: dem
  df <- df %>% 
    mutate(CAT = "dem") %>%
    relocate(CAT, .after = "TYPE") 
  
  # add sheet
  df <- df %>%
    mutate(SHEET = case_when(str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院内")~ "outpt_inpr",
                             str_detect(SHEET_jp, "外来")　&
                               str_detect(SHEET_jp, "院外")~ "outpt_outpr",
                             str_detect(SHEET_jp, "入院") ~ "inpt")) %>%
    relocate(SHEET, .after = "CAT")

  # add sheet
  df <- df %>% select(!FILE_ori)
  
  
  # fill missing cells 
  df <- df %>%
    tidyr::fill(starts_with("CLASS_"), .direction = "down")
  
  
    # process year
  # function for converting year into Western year
  convert_year <- function(x){
  if (str_detect(x, "^H")){
    y <- x %>% str_remove("^H") %>% as.numeric()
    y <- y + 1988
    return(as.character(y))
  }
  else if (str_detect(x, "^R")){
    y <- x %>% str_remove("^R") %>% as.numeric()
    y <- y + 2018
    return(as.character(y))
  }
  else{
    return(x)
  }
}
  
  # get year
  get_year <- function(x, y){
  read.xlsx(x, sheet = y, startRow = 1 , colNames = FALSE, rows = 1) %>% 
    rename(DES_jp = "X1") %>%
    mutate(FILE = x) %>%
    mutate(FILE = str_extract(FILE, "(?<=\\/)00[:digit:]+(?=\\.xlsx)")) %>%
    mutate(DES_jp = str_remove(DES_jp, "　※.+") )  %>%
    mutate(DES_jp = str_remove(DES_jp, "診療年月："))　%>%
    mutate(YEAR_str = str_extract(DES_jp, "[^年]+(?=年)")) %>%
    mutate(YEAR_end = str_extract(DES_jp, "(?<=～)[^年]+(?=年)")) %>%
    mutate(YEAR_str = convert_year(YEAR_str)) %>%
    mutate(YEAR_end = convert_year(YEAR_end))
    }
  
  df_year <- get_year(xlsx_path)
    
  df <- df %>% left_join(df_year, by = join_by(FILE))
  

  df <- df %>% mutate(across(everything(), as.character))
  
  return(df)

  }
```


```{r}
for ( i in 1:length(file_name)){
  x <- list.files(file_path[i])
  assign(df_name[i], x)
}
```

```{r}
map(folder_path, list.files) %>% unlist() %>% unique() %>% length()
```

